# Use R
language: r
sudo: true
cache: packages
warnings_are_errors: false

env:
  global:
    - BIOC_USE_DEVEL="FALSE"  ## Use the development version
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions
    - _R_CHECK_FORCE_SUGGESTS_="FALSE"  ## Some suggested packages not
                                        ## available for r-oldrel

r:
 - release

# install jags
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dependencies = TRUE)'
  # catch package installation issues sooner rather than later
  - R -e 'devtools::install_github("JEFworks/HoneyBADGER")'

# do not build vignettes...takes too long and times out on travis
script:
  - R CMD build --no-build-vignettes --no-manual .
  - R CMD check --no-build-vignettes --no-manual --timings *tar.gz

# we need to install BiocInstaller for testing Bioconductor packages
bioc_required: true

# only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
  
notifications:
  email:
    on_success: change
    on_failure: change
